### ISSUE TITLE
Update EPA dataset dashboard properties & use custom rainbow colormap for EPA datasets

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-config#119]
# What
Match the white->rainbow colormap used for EPA datasets in [this document](https://www.epa.gov/ghgemissions/gridded-2012-methane-emissions#data) in delta-config.

Not-null time density also causes un-needed time picker.

# AC
- [ ] layer sourceParams updated with custom colormap for TiTiler map layer
- [ ] layer legend stops updated to match the new colormap

# Not in AC
- There is also a problem with the lack of overviews in the COG assets for the EPA datasets, it is not in the scope of this issue to address the blurry data when zoomed > 0. ([See veda-pipelines 192](https://github.com/NASA-IMPACT/veda-data-pipelines/issues/196))

**Comment by moradology** [comment]
Skimmed the paper and couldn't find any description of how this colormap is generated. It looks as though there is a great deal of variation in the very low end of the scale (the white-to-purple region is incredibly small).
![image](https://user-images.githubusercontent.com/1977405/191857848-84758128-b593-4b84-837b-65dcb67dc362.png)
There appears to be a problem, too, when it comes to defining the color mappings we'd need. Here's an example of how that's defined: https://github.com/NASA-IMPACT/delta-config/blob/develop/datasets/epa-agriculture.data.mdx?plain=1#L28-L39
The issue here is that this gradient-based color map strategy is expecting colors that are evenly distributed across the domain. Well, given the rapid shift from white to purple, the most natural way of defining it (white, purple, blue, etc) will not produce something that resembles what is printed in the paper. Instead, we'd have to estimate the color at each (say) 1/10th of the legend and pray that what comes out after interpolation looks right.

Not sure this colormap is very good, to be honest. How important is it?

**Comment by anayeaye** [comment]
Another observation from that paper is that the maps are all composite datasets, i.e. total Agricultural methane emissions not individual emission sources. TiTiler would let us add the layers as an expression if the data were stored as multi-asset items (like HLS). If that is something we need for the EPA data, we will need to manage the STAC records differently.

**Comment by j08lue** [comment]
Also related (possible solution): multi-asset items

@anayeaye: "Data office hours" (scientist support) material?

**Comment by danielfdsilva** [comment]
There's more to this issue than simply updating the colormap on the dashboard. The tiler handling of custom colormaps also needs tweaking. Since the current solution was deemed good enough we'll consider this handled.

We'll reopen if it resurfaces.

cc @anayeaye
