### ISSUE TITLE
Publish OCO CO2 Zarr dataset?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#283]
@j08lue @anayeaye I would like to setup some automated alerts in case the xarray titiler goes down but then I think we should go ahead and add the zarr dataset to the dashboard (see https://github.com/NASA-IMPACT/veda-ui/blob/ab/add-zarr-timeseries/mock/datasets/oco2-geos-l3-daily.data.mdx) to demonstrate the capability, what do you think?

_Originally posted by @abarciauskas-bgse in https://github.com/NASA-IMPACT/veda-ui/issues/538#issuecomment-1631551763_

## Acceptance criteria

- [x] Decided whether to publish the dataset on VEDA
- [ ] Created follow-up tickets (if applicable)

**Comment by j08lue** [comment]
We would very much like to have a Zarr dataset published, so we can demonstrate (live) that our system has that capability and use it in instructional notebooks etc.

Apart from the technical aspect, I would like to quickly understand the value of that dataset. 

Can you answer this, @abarciauskas-bgse - how does the OCO CO2 Zarr dataset you mentioned here [oco2-geos-l3-daily](http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/collections/oco2-geos-l3-daily) relate to the COG-formatted one we already have [co2-mean](http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/collections/co2-mean)?

Both are daily and start in 2015, where the COG one ranges until February 2022, while the Zarr one only goes to November 2021. 🤷 

Unfortunately, I am unable to see from the metadata, how they compare in terms of lineage, because the data for th COG-formatted dataset is so poor... 🙈

**Comment by abarciauskas-bgse** [comment]
@j08lue I selected this dataset because it was already published to the STAC catalog, not based on a specific use case.

I managed to find the ticket for publishing Zarr to STAC https://github.com/NASA-IMPACT/veda-architecture/issues/202 which was completed by @slesaad 

I can dig into what is the difference in these 2 datasets, but I am also inclined to ask @ashiklom or others in EIS which Zarr dataset they might want in the dashboard first.

**Comment by j08lue** [comment]
> I am also inclined to ask @ashiklom or others in EIS which Zarr dataset they might want in the dashboard first.

Please do. Anything is better than a duplicate of something we already have, too.

**Comment by abarciauskas-bgse** [comment]
@j08lue I dug into the datasets a bit. My goal was to understand if anything was obviously different just looking at the metadata and if not, can we check if the data itself is the same. [Here is the gist, sorry it's not a bit more cleaned up](https://gist.github.com/abarciauskas-bgse/8063599d20a71b52aedd3eb7fc7cadb5)) but what I think I learned was:

* The data contact for both datasets is Brad Weir (brad.weir@nasa.gov) so if we want an official answer we should ask him?
* I _think_ the data is not the same - I believe the COG dataset is daily but represents a 16-day rolling average, where as the Zarr dataset represents data from that day only. This should be clear from the file names for the COG dataset, but also if you provide a year-long temporal extent to both datasets you get 350 time steps from the COG collection and 365 from the Zarr.
* Based on this, I would hope that the mean returned from the first 16 days of data from the Zarr dataset is the same as the value of the 16th or 17th COG for the same temporal range. This unravelled a few other issues
  * At first, I wasn't able to test this however, because I encountered a rasterio error. I think this is because the suffix of the file is not just `.tif` but `._2019-01-16.tif`
  * The metadata in these COGs all seems to be referring to 2020, not the year in the filename.
  * I'm not sure if the rolling average for days 1-16 should be represented in the day 16 file or the day 17 file
  * Because of ⬆️ I'm not sure if I should be comparing the average from the zarr dataset for days 1-16 with day 16 or day 17. Either seems to be a mismatch but I'm not sure I'm doing it right.

If you think it's worth digging into this more, I would probably email Brad Weir and whomever at EIS generated the Zarr dataset to resolve these questions.

**Comment by abarciauskas-bgse** [comment]
@j08lue I spoke to Alexey and he said this would be a good dataset to publish but an even better one would be the GPM IMERG dataset that's in prod-giovanni-cache. So I would like to spend a sprint on that this PI if possible. cc @wildintellect

**Comment by j08lue** [comment]
> So I would like to spend a sprint on that this PI if possible

That would be great, please go ahead, @abarciauskas-bgse. 🚀

**Comment by j08lue** [comment]
Neither OCO nor GPM IMERG, but we are publishing CMIP6 Zarr in

- https://github.com/NASA-IMPACT/veda-config

Closing this as completed for having a nice Zarr demo dataset.
