### ISSUE TITLE
EIS Fire Perimeters not consistent

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-config#294]
For the [EIS Fire perimeters](https://www.earthdata.nasa.gov/dashboard/data-catalog/fire/explore?position=0%7C0%7C1&datetime=2023-07-12T00%3A00%3A00.000Z) vector dataset we should be able to see the progression of  the perimeter as the datetime varies particularly for larger fires. The current behaviour in the map does not show a consistent perimeter boundary as the datetime changes; a large fire may be present at a particular location and then disappears when a consecutive day is selected. 

The perimeter collection is pointing to [https://firenrt.delta-backend.com/collections/public.eis_fire_snapshot_perimeter_nrt](https://firenrt.delta-backend.com/collections/public.eis_fire_snapshot_perimeter_nrt).

cc: @mccabete, @jsignell

**Comment by mccabete** [comment]
Hey @smohiudd  thanks for writing this up. I think I know what's going on. 

The way the https://firenrt.delta-backend.com/collections/public.eis_fire_snapshot_perimeter_nrt API is releasing the fire perimeters is to show the most recent perimeter of each fire, for up to 20 days. If a date from "t" is from yesterday it means that there are no new observations today. I think the time-slider is sliding through that "t" which really means "give me all the fires that ended on date t", not "give me all the perimeters at time "t". The largefire API's "t" is better set up for the slider, because it keeps old perimeters from each fire.

**Comment by j08lue** [comment]
Has this been resolved, actually, @mccabete and @smohiudd?

**Comment by mccabete** [comment]
Yes, this is describing a result of the data structure itself.
