### ISSUE TITLE
Revise PR template

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#333]
We have a PR template but it most often is not used correctly. Instead, we get PRs without details provided by the user, but just the content of the template:

![image](https://github.com/NASA-IMPACT/veda-config/assets/3404817/f7f9d3e9-27d2-42e8-9146-889c97fd6340)

## Acceptance criteria

- [ ] Revised PR template

**Comment by stephenkilbourn** [comment]
@j08lue - There is an existing [Github action template](https://github.com/marketplace/actions/pr-description-checker ) in the marketplace that enforces that the description has a description that is not the default template.  If that default template is unedited like in your screenshot, then the developer would see the  message `"PR description is too short and seems to not fulfill PR template, please fill in"`. (that message can be modified from the default)

I could pull in this action and give clarity in the default template so that we see something like: 
```
## Why are you creating this Pull Request?
### Please select one of the following links and follow the provided template

- [Adding Datasets or Stories](?title=Content%3A%20%3Cname%3E&expand=1&template=content.md)
- [Version Release](?title=Deploy%20vX.X.X&expand=1&template=version_release.md)
- [Other](?expand=1&template=default.md)
```

**Comment by j08lue** [comment]
That would be much appreciated, @stephenkilbourn, thanks. Same goes for these config repos:

- https://github.com/NASA-IMPACT/veda-config-eic
- https://github.com/NASA-IMPACT/veda-config-ghg

**Comment by aboydnw** [comment]
We revised this PR template with https://github.com/NASA-IMPACT/veda-config/pull/486

GHGC has their own PR template that they've been iterating on, so we should probably leave that be for now, and eic are not frequent contributors of content. When we add new instances of VEDA we should iterate on this template again to provide those new instances the most useful template
