### ISSUE TITLE
v5.9.0 Issues with Datetime in several stories

### ISSUE THREAD

**Issue by acblackford** [NASA-IMPACT/veda-config#479]
I have noticed that datetime formatting in several published stories that were previously working are no longer working following the release of v5.9.0. Attached is an example, but both time series and spatial data have these issues in a few stories such as Darnah, Burn Scar, and Lahaina. I am not sure if this is a bug or was intentional and I need to go in to these stories to fix the formatting of these dataset visualizations?

<img width="1354" alt="image" src="https://github.com/user-attachments/assets/6422958e-3355-448f-8cc1-2351321e7bb7">

**Comment by dzole0311** [comment]
I think the "DD LLL yyyy" date format error is actually expected. We didn't catch this earlier since we were running an old version of the `veda-ui` in the veda-config repo. It's probably better to just update the date format in the stories directly.

I went ahead and checked other instances and they all seem to be using the correct date formatting.

**Comment by j08lue** [comment]
The linked PR seems to fix the date formatting issue.

I checked only the Darnah flood story. https://deploy-preview-481--visex.netlify.app/stories/darnah-flood

But I noticed two other issues with the map embedded in that story:


## Embedded comparison map shows only one date

The map is meant to compares two dates (7 and 22 July), but only one date (7 July) is shown.

https://github.com/NASA-IMPACT/veda-config/blob/c4ce1c3f30304f9a3e34aaaabb229cfffa4d6550/stories/darnah-flood.stories.mdx?plain=1#L226-L233

![image](https://github.com/user-attachments/assets/48606b33-e4f2-40d9-a500-146b30647282)


## Embedded comparison map does not show raster tiles until I zoom - initial raster tile requests fail due to "Read failed"

Now, the question is whether this is a backend service issue, a data issue, or a frontend issue (whether this request is even legal).

https://openveda.cloud/api/raster/searches/register

with payload:

```json
{"filter-lang":"cql2-json","filter":{"op":"and","args":[{"op":">=","args":[{"property":"datetime"},"2023-09-07T00:00:00.000Z"]},{"op":"<=","args":[{"property":"datetime"},"2023-09-07T23:59:59.999Z"]},{"op":"eq","args":[{"property":"collection"},"darnah-flood"]}]}}
```

responded with:

```json
    "links": [
        {
            "href": "https://openveda.cloud/api/raster/searches/27e9884f37bd3fc632658a84644b68dd/info",
            "rel": "metadata",
            "title": "Mosaic metadata"
        },
        {
            "href": "https://openveda.cloud/api/raster/searches/27e9884f37bd3fc632658a84644b68dd/{tileMatrixSetId}/tilejson.json",
            "rel": "tilejson",
            "templated": true,
            "title": "Link for TileJSON (Template URL)"
        },
        {
            "href": "https://openveda.cloud/api/raster/searches/27e9884f37bd3fc632658a84644b68dd/{tileMatrixSetId}/WMTSCapabilities.xml",
            "rel": "wmts",
            "templated": true,
            "title": "Link for WMTS (Template URL)"
        }
    ]
}
```

and then tile requests like

https://openveda.cloud/api/raster/searches/27e9884f37bd3fc632658a84644b68dd/tiles/WebMercatorQuad/13/4611/3306?assets=cog_default&bidx=1&title=VEDA+Dashboard+Render+Parameters&rescale=0%2C5000&resampling=bilinear&colormap_name=magma

fail with a 500 and

```json
{"detail":"Read failed. See previous exception for details."}
```
