### ISSUE TITLE
Configure Dataset metadata via UI

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-config#93]
## Description

The goal of this ticket is to test out the value of configuring the dashboard via some UI. This would be a first slice of a much larger feature/epic. 
- We can use the current netlify preview that is created on a PR
- In the future, we can solve the issue of providing a real-time preview so people don't have to go to a PR to view the preview
- In the meantime, we should share this solution with scientists and people who are configuring datasets for feedback

## Acceptance Criteria
- [ ] Given I have access to the configuration UI, when I create a new dataset in the configuration UI then I can see that dataset in my specified thematic area with the configured title, cover image and description text appearing
- [ ] Given I have access to the configuration UI, when I identify a new dataset in the configuration UI as a featured dataset then when I view the dashboard it appears as a featured dataset
- [ ] Given I have access to the configuration UI, when I identify the layers of a new dataset in the configuration UI then I can view those layers in the map explorer of the dashboard
- [ ] Include message to the users that if they want to configure overview content then go to github, reach out to team, etc

Not In Scope:
- [ ] Given I have access to the configuration UI, when I create a new dataset in the configuration UI then I can configure the overview content of that dataset with ability to insert UI elements/figures
- [ ] Real-time preview

**Comment by hanbyul-here** [comment]
We would need to scope the original needs better after user testing this proof of concept.

**Comment by aboydnw** [comment]
Relating to https://github.com/NASA-IMPACT/delta-ui/pull/224

**Comment by j08lue** [comment]
I see a lot of value in enabling data contributors to visualize (a sample of) their data as they would like it to show in the Dashboard (via the tiling service) early on in the ingestion process. That way, they can discover rendering issues due to malformatted data or other errors in the data early, before they ingest a lot of data that has to be replaced manually later. We had a couple of these cases in the latest wave of ingestions: users only discovered bad data after they had ingested several rasters and configured the dataset for the Dashboard and got the CD pull request deployment. Fixing was costly.

This could be part of improving the ingestion flow on the Data Services side, but perhaps we could also work together on some kind of UI for data ingestion that involves part of the configuration (color map selection etc) as some of the first steps. What do you think?

**Comment by danielfdsilva** [comment]
@j08lue That's an interesting use case and definitely helpful.
I'm wondering whether [titiler's cog viewer](https://staging-raster.delta-backend.com/cog/viewer) isn't enough for this first pass. Are there any specific preview options you think are missing?
